# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments']
    App\Controller\Api\:
        resource: '../src/Controller/Api'
        tags: ['controller.service_arguments']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\Api\UserController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $eventDispatcher: '@event_dispatcher'
            $tokenStorage: '@security.token_storage'

    App\Controller\Admin\UserController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $eventDispatcher: '@event_dispatcher'
            $tokenStorage: '@security.token_storage'

    App\Controller\Api\ProductController:
        arguments:
            $paginator: '@knp_paginator'

    app.form.registration:
        class: App\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    redirect.after.login:
        class: App\Helper\AfterLoginRedirection
        arguments: ['@router']

    tenant_user_service:
        class: App\Service\UserService
        arguments: [ '@security.token_storage' ]

    token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.orm.entity_manager']